# Generated by Django 5.0.14 on 2025-12-18 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0005_ingredienteplantilla_auditoria_i_plato_p_92feed_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platoobservado',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='platos/'),
        ),
    ]
